### ISSUE TITLE
Revise Lab 1 Document

### ISSUE THREAD

**Issue by Justin-Terry** [Justin-Terry/SafeHopper#1]
We need to revise our lab 1 document to include an executive summary. Consider adding a title page and possibly better formatting for a more finished look.

**Comment by Andrew-Delgado** [comment]
Got it, I also think Justin and I need to make sure our diagrams are consistent with the stakeholders(developers, implementers, testers...)

**Comment by Justin-Terry** [comment]
@Andrew-Delgado are you happy with the updated lab 1 document? If so lets go ahead and mark this as finished.

**Comment by Andrew-Delgado** [comment]
@Justin-Terry Yes,  I am happy with the updated version. I just need to add on my System Vision to the end of the document after I export everyone else's part as a pdf. Once I do that I will mark it as finished.
