### ISSUE TITLE
ER Diagram

### ISSUE THREAD

**Issue by Andrew-Delgado** [Justin-Terry/SafeHopper#51]
"ER diagram and description: Provide an entity relationship diagram of all the data that
is represented in your system. You can start eliciting that data from the nouns in your use
case scenario descriptions. Make sure they all have attributes, keys and relationships
where appropriate."

**Comment by Justin-Terry** [comment]
https://creately.com/diagram/jsdr3xpt1/bPqaCMlCXTLKKcafC13Dls3FCE%3D
