### ISSUE TITLE
Class Diagrams

### ISSUE THREAD

**Issue by Andrew-Delgado** [Justin-Terry/SafeHopper#55]
"Class diagram(s) and description: Develop a class diagram from your ER diagram and
specify the classes, attributes, their data types, operations or methods, and the relations
between the classes, including inheritance hierarchies. Think of how to structure your
system into packages and how the classes should be grouped into those packages.
Elaborate a class diagram of your system that demonstrates that you know how to design
good, modular software and that you have understood how to use design patterns (use
inheritance, use model-view-controller or a different pattern you find useful in your
design). Make sure you point out where you used design patterns in your architecture"

**Comment by Justin-Terry** [comment]
https://creately.com/diagram/jskubz1y1/eNZ3KHfw7okV9026meAKo1xs%3D
