### ISSUE TITLE
Mock-ups - Vertical

### ISSUE THREAD

**Issue by Andrew-Delgado** [Justin-Terry/SafeHopper#56]
"Mock-ups of horizontal and vertical prototype: Provide mock-ups in the form of wire
frames or actual screenshots of your future user interface. The horizontal prototype
shows an overview of all the functionality of the system and a site map that includes all screens. The vertical prototype shows a walk through a major functionality (e.g. the steps
for finding an open classroom for studying with a group of students)."

**Comment by Justin-Terry** [comment]
https://creately.com/diagram/jsmbnh7e3/OpQl7gF8QmbTp0OdOVPfLxit8%3D
